[package]
name = "wluma"
version = "4.3.0"
authors = ["Maxim Baz", "Cyril Levis"]
edition = "2021"

[dependencies]
wayland-client = { version = "0.30" }
wayland-backend = { version = "0.2", features = ["dlopen"] }
wayland-protocols = { version = "0.30", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.1", features = ["client"] }
smithay-client-toolkit = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.7.6"
chrono = "0.4"
ash = { version = "0.37.3", features = ["linked"], default-features = false }
itertools = "0.11"
v4l = { version = "0.14.0", features = ["libv4l"], default-features = false }
ddc-hi = "0.4"
log = "0.4"
env_logger = "0.10"
inotify = "0.10"
lazy_static = "1.4"
xdg = "2.5.2"
dbus = "0.9.7"

[dev-dependencies]
mockall = "0.11.4"
